//
//  TungPodcastStyleKit.h
//  Tung
//
//  Created by Jamie Perkins on 10/2/15.
//  Copyright (c) 2015 Inorganik Produce, Inc. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface TungPodcastStyleKit : NSObject

// Colors
+ (UIColor*)tungColor;
+ (UIColor*)tungColorMediumLight;

// Drawing Methods
+ (void)drawSubscribeIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawDonateIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawRecommendIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawCommentIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawClipIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawQueueIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawSaveIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawCancelIconWithColor: (UIColor*)color;
+ (void)drawCheckmarkIconWithColor: (UIColor*)color;
+ (void)drawShareIconWithColor: (UIColor*)color;
+ (void)drawWebsiteIconWithColor: (UIColor*)color;
+ (void)drawPlayIconWithColor: (UIColor*)color;
+ (void)drawStopIconWithColor: (UIColor*)color;
+ (void)drawRecordIconWithColor: (UIColor*)color;
+ (void)drawSubscribeIconSolidWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawHideIconWithColor: (UIColor*)color;
+ (void)drawShowIconWithColor: (UIColor*)color;
+ (void)drawAddCircleIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawOptionsIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawTwitterIconWithFrame: (CGRect)frame color: (UIColor*)color on: (BOOL)on;
+ (void)drawFacebookIconWithFrame: (CGRect)frame color: (UIColor*)color on: (BOOL)on;
+ (void)drawNowPlayingIconWithFrame: (CGRect)frame color: (UIColor*)color;
+ (void)drawSubscribeButtonWithFrame: (CGRect)frame color: (UIColor*)color on: (BOOL)on down: (BOOL)down;
+ (void)drawClipButtonWithFrame: (CGRect)frame down: (BOOL)down;
+ (void)drawRecommendButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down;
+ (void)drawShareButtonWithFrame: (CGRect)frame down: (BOOL)down;
+ (void)drawWebsiteButtonWithFrame: (CGRect)frame down: (BOOL)down disabled: (BOOL)disabled;
+ (void)drawSupportButtonWithFrame: (CGRect)frame color: (UIColor*)color down: (BOOL)down;
+ (void)drawClipRecordButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down disabled: (BOOL)disabled;
+ (void)drawClipPlayButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down disabled: (BOOL)disabled;
+ (void)drawClipCancelButtonWithFrame: (CGRect)frame down: (BOOL)down disabled: (BOOL)disabled;
+ (void)drawClipOkButtonWithFrame: (CGRect)frame down: (BOOL)down disabled: (BOOL)disabled;
+ (void)drawHideControlsButtonWithFrame: (CGRect)frame;
+ (void)drawShowControlsButtonWithFrame: (CGRect)frame;
+ (void)drawCommentButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down disabled: (BOOL)disabled;
+ (void)drawTwitterButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down;
+ (void)drawFacebookButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down;
+ (void)drawPillTextbuttonWithFrame: (CGRect)frame down: (BOOL)down disabled: (BOOL)disabled buttonText: (NSString*)buttonText;
+ (void)drawSpeedButtonWithFrame: (CGRect)frame down: (BOOL)down buttonText: (NSString*)buttonText;
+ (void)drawSaveButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down;
+ (void)drawTungButtonOnWhiteWithFrame: (CGRect)frame down: (BOOL)down buttonText: (NSString*)buttonText;
+ (void)drawFollowButtonWithFrame: (CGRect)frame on: (BOOL)on down: (BOOL)down buttonText: (NSString*)buttonText;
+ (void)drawTextAreaBkgdWithFrame: (CGRect)frame;

@end
