//
//  TungStyleKit.h
//  tung
//
//  Created by Jamie Perkins on 1/6/15.
//  Copyright (c) 2015 Inorganik Produce, Inc. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface TungStyleKit : NSObject

// Colors
+ (UIColor*)tungPurple;
+ (UIColor*)sayIt;
+ (UIColor*)music;
+ (UIColor*)singIt;
+ (UIColor*)sampled;
+ (UIColor*)foodAndDrink;
+ (UIColor*)shoutIt;
+ (UIColor*)nature;
+ (UIColor*)sounds;
+ (UIColor*)tungColorDark;
+ (UIColor*)tungColorMediumLight;

// Drawing Methods
+ (void)drawTungButtonOnWhiteWithFrame: (CGRect)frame pressed: (BOOL)pressed buttonText: (NSString*)buttonText;
+ (void)drawFollowButtonWithFrame: (CGRect)frame pressed: (BOOL)pressed buttonText: (NSString*)buttonText on: (BOOL)on;
+ (void)drawPostButtonWithFrame: (CGRect)frame pressed: (BOOL)pressed postButtonText: (NSString*)postButtonText;
+ (void)drawChangeRecordMethodWithFrame: (CGRect)frame on: (BOOL)on;
+ (void)drawIconPlayCountWithFrame: (CGRect)frame;
+ (void)drawIconLikeWithFrame: (CGRect)frame on: (BOOL)on;
+ (void)drawIconEchoWithFrame: (CGRect)frame on: (BOOL)on disabled: (BOOL)disabled;
+ (void)drawIconPlayedWithFrame: (CGRect)frame;
+ (void)drawIconPlayingWithFrame: (CGRect)frame;
+ (void)drawIconEchoSmallWithFrame: (CGRect)frame;
+ (void)drawIconOptionsWithFrame: (CGRect)frame;
+ (void)drawIconLikeSmallWithFrame: (CGRect)frame;
+ (void)drawIconAddSmallWithFrame: (CGRect)frame;

@end
